// Synthesises firmware-style telemetry so the plotter can be exercised without
// any hardware attached.
//
// This matters most for the desktop build, where the Web Serial bridge is a
// stub and no data can ever arrive. The generated bytes are pushed through
// SerialBridge::feedBytes(), i.e. the exact same path real serial data takes,
// so the demo also exercises the UTF-8 decode, the line splitting and the
// key=value parser -- not just the charts.
#pragma once

#include <QObject>
#include <QTimer>

class DemoSource : public QObject
{
    Q_OBJECT
public:
    explicit DemoSource(QObject *parent = nullptr);

    void start();
    void stop();
    bool isActive() const { return m_timer.isActive(); }

private:
    void tick();

    QTimer m_timer;
    quint32 m_ms = 0;        // fake millis(), mirrors the firmware's t=
    quint32 m_beat = 0;
    double m_tgt = 0.0;
    double m_vel = 0.0;
    double m_pos = 0.0;
    double m_iq = 0.0;
};
